### ISSUE TITLE
refactor homepage

### ISSUE THREAD

**Issue by phodal** [phodal/phodaldev#5]

**Comment by phodal** [comment]
New Logo

**Comment by phodal** [comment]
Interviews, Articles, Open Source Projects

**Comment by phodal** [comment]
Blog Detail UI:

http://blog.jupo.org/
https://medium.com/
http://www.15yan.com/
http://www.jianshu.com/
http://www.hug8217.com/

**Comment by phodal** [comment]
http://pivotal.io/

**Comment by zh-h** [comment]
又没有数据库模型？我不懂python，没办法参考数据库设计。

**Comment by phodal** [comment]
@zh-h 用的是默认的数据库。这个issue是写给自己的
